/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui;

import java.time.LocalDate;
import java.time.Month;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import negocio.Adulto;
import negocio.Menor;
import negocio.Paciente;
import negocio.PacienteJaExisteException;
import negocio.ResponsavelnvalidoException;
import negocio.SistemaVacinas;
import static util.Util.convertData;
import static util.Util.verificaData;

/**
 *
 * @author anton
 */
public class FrameCadastraMenor extends javax.swing.JFrame {
    
    static SistemaVacinas sistema = SistemaVacinas.getInstance();

    /**
     * Creates new form FrameCadastraMenor
     */
    public FrameCadastraMenor() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextPacienteNome = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextPacienteNascimento = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextMenorCPF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextResponsavelCPF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaListarPacientes = new javax.swing.JTextArea();
        jButtonCadastrarMenor = new javax.swing.JButton();
        jButtonListarPacientes = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setText("Nome: ");

        jTextPacienteNome.setText("(Texto)");
        jTextPacienteNome.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPacienteNomeFocusGained(evt);
            }
        });
        jTextPacienteNome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextPacienteNomeMouseClicked(evt);
            }
        });
        jTextPacienteNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextPacienteNomeActionPerformed(evt);
            }
        });

        jLabel2.setText("Nascimento:");

        jTextPacienteNascimento.setText("(dd/MM/aaaa)");
        jTextPacienteNascimento.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextPacienteNascimentoFocusGained(evt);
            }
        });

        jLabel3.setText("CPF Menor: ");

        jTextMenorCPF.setText("(Texto)");
        jTextMenorCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextMenorCPFFocusGained(evt);
            }
        });
        jTextMenorCPF.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextMenorCPFMouseClicked(evt);
            }
        });

        jLabel4.setText("CPF Responsável:");

        jTextResponsavelCPF.setText("(Texto)");
        jTextResponsavelCPF.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jTextResponsavelCPFFocusGained(evt);
            }
        });

        jTextAreaListarPacientes.setEditable(false);
        jTextAreaListarPacientes.setBackground(new java.awt.Color(51, 51, 51));
        jTextAreaListarPacientes.setColumns(20);
        jTextAreaListarPacientes.setForeground(new java.awt.Color(0, 204, 51));
        jTextAreaListarPacientes.setRows(5);
        jScrollPane1.setViewportView(jTextAreaListarPacientes);

        jButtonCadastrarMenor.setText("Cadastrar Menor");
        jButtonCadastrarMenor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarMenorActionPerformed(evt);
            }
        });

        jButtonListarPacientes.setText("Listar Pacientes");
        jButtonListarPacientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonListarPacientesActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Cadastro de Paciente Menor");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextMenorCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextResponsavelCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPacienteNascimento, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextPacienteNome, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 463, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButtonCadastrarMenor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonListarPacientes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(237, 237, 237))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextPacienteNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextPacienteNascimento, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextMenorCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextResponsavelCPF, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonCadastrarMenor)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonListarPacientes))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextPacienteNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextPacienteNomeActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextPacienteNomeActionPerformed

    private void jTextPacienteNomeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPacienteNomeFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextPacienteNomeFocusGained

    private void jTextPacienteNomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextPacienteNomeMouseClicked
        // TODO add your handling code here:
        jTextPacienteNome.setText(null);
    }//GEN-LAST:event_jTextPacienteNomeMouseClicked

    private void jTextPacienteNascimentoFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextPacienteNascimentoFocusGained
        // TODO add your handling code here:
        jTextPacienteNascimento.setText(null);
    }//GEN-LAST:event_jTextPacienteNascimentoFocusGained

    private void jTextMenorCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextMenorCPFFocusGained
        // TODO add your handling code here:
        jTextMenorCPF.setText(null);
    }//GEN-LAST:event_jTextMenorCPFFocusGained

    private void jTextMenorCPFMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextMenorCPFMouseClicked
        // TODO add your handling code here:
        jTextMenorCPF.setText(null);
    }//GEN-LAST:event_jTextMenorCPFMouseClicked

    private void jTextResponsavelCPFFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jTextResponsavelCPFFocusGained
        // TODO add your handling code here:
        jTextResponsavelCPF.setText(null);
    }//GEN-LAST:event_jTextResponsavelCPFFocusGained

    private void jButtonCadastrarMenorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarMenorActionPerformed
        // TODO add your handling code here:
        String vNome = jTextPacienteNome.getText();
        String vNascimento = jTextPacienteNascimento.getText();
        String vMenorCPF = jTextMenorCPF.getText();
        String vResponsavelCPF = jTextResponsavelCPF.getText();
        try{
            if(vNome.isBlank()||vNascimento.isBlank()||vMenorCPF.isBlank()||vResponsavelCPF.isBlank()){
                throw new CampoVazioException();
            }
            if(!verificaData(vNascimento)){
                throw new FormatoDataInvalidoException();
            }
            if(sistema.getAdulto(vResponsavelCPF)==null){
                throw new ResponsavelnvalidoException("Responsavel Invalido");
            }
            
            sistema.cadastrarPaciente(new Menor(vNome,convertData(vNascimento),vMenorCPF,sistema.getAdulto(vResponsavelCPF)));
            
            JOptionPane.showMessageDialog(rootPane, "Menor Cadastrado com Sucesso!");
            
            jTextPacienteNome.setText(null);
            jTextPacienteNascimento.setText(null);
            jTextMenorCPF.setText(null);
            jTextResponsavelCPF.setText(null);
            
        }catch(CampoVazioException | FormatoDataInvalidoException | ResponsavelnvalidoException | PacienteJaExisteException ex){
            
            JOptionPane.showMessageDialog(rootPane, "Paciente Não Cadastrado \n" + ex.getMessage());
            
        }
    }//GEN-LAST:event_jButtonCadastrarMenorActionPerformed

    private void jButtonListarPacientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonListarPacientesActionPerformed
        // TODO add your handling code here:
        jTextAreaListarPacientes.setText("");
        for (Iterator<Paciente> i = sistema.todosPacientes(); i.hasNext(); ){ 
            //System.out.println(i.next());
            jTextAreaListarPacientes.append(i.next().toString()+"\n");
        }
    }//GEN-LAST:event_jButtonListarPacientesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) throws PacienteJaExisteException, ResponsavelnvalidoException {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrameCadastraMenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrameCadastraMenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrameCadastraMenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrameCadastraMenor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        
        Adulto p1 = new Adulto("Damiao",LocalDate.of(1990, Month.AUGUST, 20), "38457482","Rua Dali" );
        Menor p2 = new Menor("Rodrigo",LocalDate.of(2015, Month.SEPTEMBER, 12), "998759999", p1 );
        
        sistema.cadastrarPaciente(p1);
        sistema.cadastrarPaciente(p2);
        
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrameCadastraMenor().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCadastrarMenor;
    private javax.swing.JButton jButtonListarPacientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextAreaListarPacientes;
    private javax.swing.JTextField jTextMenorCPF;
    private javax.swing.JTextField jTextPacienteNascimento;
    private javax.swing.JTextField jTextPacienteNome;
    private javax.swing.JTextField jTextResponsavelCPF;
    // End of variables declaration//GEN-END:variables
}
